# Generated by Django 3.1.7 on 2021-03-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210301_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fullname',
            new_name='lastname',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
