# Generated by Django 3.1.7 on 2021-02-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210220_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo7',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo8',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo9',
        ),
        migrations.RemoveField(
            model_name='product',
            name='video',
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=39.99, max_digits=20),
        ),
    ]
